name: Dependency Updates

on:
  schedule:
    - cron: '0 9 * * 1'  # Weekly on Monday at 9 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-updates:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Check for outdated packages
        run: |
          echo "📦 Checking for dependency updates..."
          ncu
          ncu --json > updates.json || echo "No updates available"

      - name: Show update report
        run: |
          if [ -f updates.json ]; then
            echo "Updates available:"
            cat updates.json
          else
            echo "✅ All dependencies are up to date"
          fi

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run security audit (read-only)
        run: |
          echo "🔒 Running security audit..."
          npm audit --audit-level=moderate || echo "Audit completed with findings"

      - name: Create package-lock for security fixes
        run: npm i --package-lock-only

      - name: Try security fixes (optional)
        run: |
          npm audit fix --dry-run || echo "Dry run completed"
          echo "Manual review required for security updates"

  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    needs: [check-updates, security-audit]
    if: always()
    steps:
      - name: Summary
        run: |
          echo "📋 Dependency Update Summary"
          echo "- Check Updates: ${{ needs.check-updates.result }}"
          echo "- Security Audit: ${{ needs.security-audit.result }}"
          echo "✅ Dependency check completed"