name: Deployment Pipeline

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  NODE_VERSION: '22'

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
      - name: Build for production
        run: npm run build
        env:
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
          retention-days: 30

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
      url: https://staging.heavens-above.app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist/

      - name: Deploy to GitHub Pages (Staging)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages-staging
          cname: staging.heavens-above.app

      - name: Notify deployment status
        run: |
          echo "✅ Staging deployment successful"
          echo "URL: https://staging.heavens-above.app"

  test-staging:
    name: Test Staging Environment
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for deployment
        run: sleep 30

      - name: Run smoke tests
        run: |
          curl -f https://staging.heavens-above.app || exit 1
          echo "✅ Smoke tests passed"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test-staging
    environment:
      name: production
      url: https://heavens-above.app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist/

      - name: Deploy to GitHub Pages (Production)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: heavens-above.app

      - name: Create deployment record
        run: |
          echo "Deployment completed at $(date)" >> deployment.log
          echo "Commit: ${{ github.sha }}" >> deployment.log

      - name: Notify deployment success
        run: |
          echo "🚀 Production deployment successful"
          echo "URL: https://heavens-above.app"
          echo "Commit: ${{ github.sha }}"

  rollback:
    name: Rollback on Failure
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Rollback to previous version
        run: |
          echo "⚠️ Deployment failed. Initiating rollback..."
          git checkout HEAD~1
          
      - name: Notify team
        run: |
          echo "Rollback initiated. Please investigate the deployment failure."