name: Documentation Deployment

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'README.md'
      - '*.md'
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
      - '*.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Create documentation structure
        run: |
          mkdir -p docs/build
          
          # Copy all markdown files to build directory
          cp -r docs/*.md docs/build/ 2>/dev/null || echo "No markdown files to copy"
          
          # Create index.html
          cat > docs/build/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Heavens Above - Documentation</title>
            <style>
              body {
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                line-height: 1.6;
              }
              h1 { color: #2c3e50; }
              h2 { color: #3498db; margin-top: 30px; }
              .nav { background: #f4f4f4; padding: 15px; margin-bottom: 20px; }
              .nav a { margin-right: 15px; color: #3498db; text-decoration: none; }
              .nav a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <div class="nav">
              <a href="index.html">Home</a>
              <a href="README.html">Documentation</a>
              <a href="getting-started.html">Getting Started</a>
              <a href="user-guide.html">User Guide</a>
            </div>
            
            <h1>Heavens Above - Documentation</h1>
            
            <h2>Welcome</h2>
            <p>Welcome to the Heavens Above project documentation. This astronomy visualization application helps you explore celestial objects and astronomical events.</p>
            
            <h2>Quick Links</h2>
            <ul>
              <li><a href="https://github.com/Amnaaaaaaaaaaaa/heavens-above">GitHub Repository</a></li>
              <li><a href="README.html">Full Documentation</a></li>
              <li><a href="getting-started.html">Getting Started Guide</a></li>
            </ul>
            
            <h2>About</h2>
            <p>This documentation was automatically generated and deployed using GitHub Actions.</p>
            <p>Last updated: <span id="date"></span></p>
            <script>document.getElementById('date').textContent = new Date().toLocaleString();</script>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: gh-pages-docs
          force_orphan: true

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/
          retention-days: 30

      - name: Deployment summary
        if: github.event_name == 'push'
        run: |
          echo "📚 Documentation deployed successfully"
          echo "Branch: gh-pages-docs"
          echo "Commit: ${{ github.sha }}"