name: Documentation Deployment

on:
  push:
    branches: [main, master]
    paths:
      - 'docs/**'
      - 'README.md'
      - '*.md'
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
      - '*.md'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install documentation tools
        run: |
          npm install -g jsdoc
          npm install -g markdown-it
          npm install -g docsify-cli

      - name: Generate API documentation
        run: |
          mkdir -p docs/api
          jsdoc -r -d docs/api src/ || echo "JSDoc completed"

      - name: Build markdown documentation
        run: |
          mkdir -p docs/build
          # Convert README to HTML
          npx markdown-it README.md > docs/build/index.html || echo "Markdown processing completed"

      - name: Generate documentation index
        run: |
          cat > docs/build/README.md << 'EOF'
          # Heavens Above - Documentation
          
          ## Table of Contents
          
          - [Getting Started](getting-started.html)
          - [API Reference](api/index.html)
          - [User Guide](user-guide.html)
          
          ## Quick Links
          
          - [GitHub Repository](https://github.com/stevenjoezhang/heavens-above)
          - [Live Demo](https://stevenjoezhang.github.io/heavens-above)
          
          ---
          
          Last updated: $(date)
          EOF

      - name: Create basic HTML structure
        run: |
          cat > docs/build/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Heavens Above - Documentation</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
                  h1 { color: #4a90e2; }
                  .container { max-width: 800px; margin: 0 auto; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Heavens Above Documentation</h1>
                  <p>Welcome to the Heavens Above project documentation.</p>
                  <p>This documentation is automatically generated and deployed.</p>
                  <p><a href="README.md">View Documentation</a></p>
              </div>
          </body>
          </html>
          EOF

      - name: Validate documentation
        run: |
          echo "Validating documentation structure..."
          test -f docs/build/index.html || exit 1
          echo "✅ Documentation structure valid"

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/
          retention-days: 30

  deploy-docs:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: docs/build/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

      - name: Deployment summary
        run: |
          echo "📚 Documentation deployed successfully"
          echo "URL: ${{ steps.deployment.outputs.page_url }}"